---
title: "Interesting challanges"
output:
 html_document:
  toc: true
  toc_depth: 1
  toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These problems are challenging, but require only basic undergraduate mathematics, at most. Some are olympiad style questions, others are either classics, with origin unknown or from the Stanford and Putnam examinations.

<br>

# Random contractions

__Let $R(n)$ be a random draw of integers between 0 and $n − 1$, inclusive. I repeatedly
apply $R$, starting at $10^{100}$. What is the expected number of repeated applications until
I get zero.__

Answer [here](pdfs/contract.pdf)

# Counting products

__Consider all 100 digit numbers, i.e. those between 0 to $10^{100}$ − 1, inclusive. For each
number, take the product of non-zero digits (treat the product of digits of 0 as 1), and
sum across all the numbers. What’s the last digit?__

Answer [here](pdfs/prods.pdf)

# Stick breaking

Stick breaking has a long history in mathematics. For instance we can ask, for the the probability that we can form a triangle from the segments of a broken stick. More generally, we can ask for the probability of forming a $n$-gon after making $n$ breaks (resulting in $n+1$ segments).

A Shiny interactive app to investigating segment lengths in the $n$ break case can be found under the R section of the [Code tab](code.html#deployment:_shiny_and_knitr) on this site. Tap [here](https://chris-x.shinyapps.io/StickBreak/) to launch the app.

## Expected length of $n$ segments

__If I break a stick of unit length into $n$ random pieces, what's the expected
length of the largest piece?__

Answer [here](pdfs/stick_1.pdf)

## Expected length of ratio of 2 segments

__If I break a stick of unit length into 2 pieces, what is the average size of the smaller piece?
What is the average ratio of the smaller length to the larger length?__

Answer [here](pdfs/stick_2.pdf)
