---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# C1-C4 EdExcel

<br>

In any handwritten notes, my comments / suggestions are in blue or surrounded by square brackets [].

Please take a look through C3 2014. I will go through this next time.

Model answers
[C3 2014](pdfs/JR/c3_june_2014_model_answers.pdf) 

Topics to focus on:

* Graphs, curves and functions 
* Integration
* Trig
* Differentiation

These two topics can be covered/started by self-study, although I will spend some time on these.

* C4 Vectors
* C2 Sequences and series

Topics to practice: Chain rule and product rule.

For Q3 C3 2014, we used implicit differentiation. This comes from the chain rule. The easiest way to learn the chain rule is by using the $u$ substitution. 

Say we are given a functon $y=g(x)$ where $g$ is complicated and we need to calculate the derivative $dy/dx$. Then applying the chain-rule is the same as expressing $f$ using two simpler functions: $u(x)$ and $f(u)$ before differentiating the function of a function.
\[
y=g(x) = f(u(x))
\]

First we practice making the $u$ substituion.

1.
\[
y=(3x^{2}-5x)^3, \quad \textrm{take } u(x)=3x^{2}-5x, \: f(u)=u^{3}
\]

2.
\[
y=\sqrt{2x^{3}+x^{2}}, \quad \textrm{take } u(x)=2x^{3}+x^{2}, \: f(u)=\sqrt{u}
\]

To differentiate a function of a function, we use the __chain rule__. With the $u$ substition above, we can write the chain rule as
\[
\frac{dy}{dx}=\frac{dy}{du} \times \frac{du}{dx}
\]

Imagine the terms $dy,du,dx$ were just like normal fractions. Notice how the $du$ terms cancel, leaving $dy/dx$.
With the chain rule - it is important to (where possible) check any differentiation results when __not using__ the chain rule.

1. Compute $dy/dx$ when $y=(3x^{2}-5x)^3$.

Method: chain rule
\begin{align}
&\textrm{Let } \:u=3x^{2}-5x \:\: \textrm{then }\: y=u^{3}\\
&\textrm{using the chain rule: }\: \frac{dy}{dx}=\frac{dy}{du}\frac{du}{dx}\\
& \frac{dy}{du}=3u^{2}, \quad \frac{du}{dx}=6x-5\\
&\frac{dy}{dx}=3u^{2}(6x-5)=3(3x^{2}-5x)^{2}(6x-5)
\end{align}
If we expand this out we get $dy/dx=162x^5-675x^4+900x^3-375x^2$.

Method: long-hand (expanding)
\begin{align}
&y=(3x^{2}-5x)^{3}=27x^6-135x^5+225x^4-125x^3\\
&\textrm{differentiating term-by-term: }\\
& \frac{dy}{dx}=(6)(27)x^{5}-(5)(135)x^{4}+(4)(225)x^{3}-(3)(125)x^{2}\\
&\frac{dy}{dx}=162x^5-675x^4+900x^3-375x^2
\end{align}

So we see the chain rule gives us exactly the same answer. It is just easier to differentiate (rather than expanding and doing lots of algebra).
<br>

2. Compute $dy/dx$ when $y=\sqrt{2x+x^{2}}$.

Method: chain rule
\begin{align}
&\textrm{Let } \:u=2x+x^{2} \:\: \textrm{then }\: y=u^{1/2}\\
&\textrm{using the chain rule: }\: \frac{dy}{dx}=\frac{dy}{du}\frac{du}{dx}\\
& \frac{dy}{du}=1/2u^{-1/2}, \quad \frac{du}{dx}=2+2x=2(1+x)\\
&\frac{dy}{dx}=1/2u^{-1/2}2(1+x)=\frac{1+x}{\sqrt{2x+x^{2}}}
\end{align}

3. A special case of the chain rule is used when we are given $x$ in terms of $y$, and the equation cannot be rearranged as $y$ in terms of $x$ easily. For example
$x=y+y^{1/3}-2y^{2}$ cannot (easily) be written with $y$ the subject ($y=...$). But we can still find $dy/dx$.

__DO NOT NEED TO KNOW DERIVATION FOR EXAM__ - but helps understanding.

__DO NEED TO KNOW RESULT__
\begin{align}
&x=f(y) \quad \textrm{take derivative wrt $x$ of BOTH sides}\\
&\frac{dx}{dx}=\frac{d f(y)}{dx} \quad \textrm{y is really $y(x)$}\\
& 1=\frac{d(f(y))}{dy}\frac{dy}{dx}\quad \textrm{by chain rule} \\\\
&\frac{1}{\frac{d(f(y))}{dy}}=\frac{dy}{dx} \quad \textrm{But $f(y)=x$ so we can substitute this}\\\\
&\frac{1}{\frac{dx}{dy}}=\frac{dy}{dx}
\end{align}

Using the example above find $dy/dx$ when $x=y+y^{1/3}-2y^{2}$
\[
\frac{dx}{dy}=1+(1/3)y^{-2/3}-4y \implies \frac{dy}{dx}=\frac{1}{1+(1/3)y^{-2/3}-4y}
\]
Sometimes we may be able to use the original equation to write $dy/dx$ in terms of $x$, but otherwise just leave it in terms of $y$.

4. Differentiating $e^{f(x)}$ and $\log(f(x))$

It is really important to learn these rules off by heart. These results just follow from the chain rule
\begin{align}
y=e^{f(x)}, \quad \textrm{then} \quad \frac{dy}{dx}=f^{\prime}(x)e^{f(x)}\\\\
y=\log{f(x)}, \quad \textrm{then} \quad \frac{dy}{dx}=\frac{f^{\prime}(x)}{f(x)}\\
\end{align}

In particular, when $f(x)=x$ (then $f^{\prime}(x)=1$)
\begin{align}
y=e^{x}, \quad \textrm{then} \quad \frac{dy}{dx}=(1)e^{x}=e^{x}\\\\
y=\log{x}, \quad \textrm{then} \quad \frac{dy}{dx}=\frac{1}{x}\\
\end{align}

I suggest attempting around 50% of the exercises in C3 text book, Chapter 8 (Exercises 8A to 8E, this includes product and quotient rules). I also suggest revisiting C2 chapter 3 to brush up on exponentials and logarithms: work through the __worked examples__ and do some exercises only if you feel you would benefit (optional).

<br>

__Binomial expansions and integration__

Here are some integration and binomial expansion questions for self-study. More can be found in text books.

<br>

1. Show that 
$\int 8\sqrt{x}\:dx=\frac{16}{3}x^{3/2}+C$

<br>

2. By computing $\int_{1}^{2} a x^{-2}\:dx=5$, show that the constant $a=10$

<br>

3. 

a) Show that $\int x^{-4/3}\:dx=-3x^{-1/3}+C,$ where $C$ is the constant of integration. 

b) Using this result, find the value of the constant $b$ that satisfies 
\[b\int_{1}^{8} x^{-4/3}\:dx=6\]

<br>

4. Compute the value of $\int_{1}^{2}\frac{1}{x^{3}}-\frac{x^{3}}{4}\:dx$. What does this result say about the area(s) bounded by the graph of $y=\frac{1}{x^{3}}-\frac{x^{3}}{4}$, and the $x$-axis over the range $x=1$ to $x=2$?

<br>

5. By expanding brackets, show that $(1-x)^{2} +2x > 0$ for all $x$.

<br>

6. 

a) By expanding the brackets show that $(1+x)^{2}=1+2x+x^{2}$


b) By using the fact that 
\[
\frac{a^{2}}{y^{2}}=\left(\frac{a}{y}\right)^{2}
\]
make a suitable substitution for $x$, and deduce the values of $p$ and $q$ that satisfy
\[
\left(1-\frac{4}{y^{2}}\right)^{2}=1+\frac{p}{y^{2}}+\frac{q}{y^{4}}
\]

<br>

7. 

a. For $a$ a constant, by expanding the brackets show that $(a+x)^{3}=a^{3}+3a^{2}x+3ax^{2}+x^{3}$


b. Use the result of part a) to compute
\[
\int_{0}^{1} (a+x)^{3}\:dx
\]

leaving your answer in terms of the __constant__ $a$.

c. Hence, using the result to part b), find the three possible values of $a$ that satisfy


\[
\int_{0}^{1} (a+x)^{3}\:dx=\frac{1}{4}+\frac{a}{2}
\]

<br>

Answer to 7

a. Expand using binomial coefficients or by expanding brackets. 

Note1. You should be able to switch between the equivalent notations
\[
^{n}C_{r}=\binom{n}{r}=\frac{n!}{r!(n-r)!}
\]

Note2. There are lots of helpful identities involving binomial coefficients. The most important for A level is to realise
\[
\binom{n}{r}=\binom{n}{n-r}
\]
To show this, we start on the right-hand side and end up with the left-hand side simply using the definition

\[
\binom{n}{n-r}=\frac{n!}{(n-r)!(n-n+r)!}=\frac{n!}{(n-r)!r!}=\binom{n}{r}
\]

__Answering the question__

Using binomial coefficents.

\[
(a+x)^{3}=\binom{3}{0}a^{3}x^{0}+\binom{3}{1}a^{2}x^{1}+\binom{3}{2}a^{1}x^{2}+\binom{3}{3}a^{0}x^{3}
\]
First,
\[
\binom{3}{0}=\frac{3!}{0!(3-0)!}=\frac{3!}{3!}=1 =\binom{3}{3}, \:\: \textrm{ by the above result (Note2)}
\]
Similarly,

\[
\binom{3}{1}=\frac{3!}{1!(3-1)!}=\frac{3!}{2!}=3 =\binom{3}{2}, \:\: \textrm{ by the above result (Note2)}
\]

<br>

Now we can simplify the terms in $(a+x)^{3}$

\[
(a+x)^{3}=a^{3}+3a^{2}x+3ax^{2}+x^{3}
\]

<br>

We can also expand the brackets

\begin{align}
(a+x)^{3}=(a+x)(a+x)^{2}&=(a+x)(a^{2}+2ax+x^{2})\\
&=(a^{3}+2a^{2}x+ax^{2}+a^{2}x+2ax^{2}+x^{3})\\
&=a^{3}+3a^{2}x+3ax^{2}+x^{3}
\end{align}

<br>

b. 
\begin{align}
\int_{0}^{1}(a+x)^{3}\:dx &=\int_{0}^{1} a^{3}+3a^{2}x+3ax^{2}+x^{3}\:dx\\
&=\left[a^{3}x+3a^{2}\frac{x^{2}}{2}+3a\frac{x^{3}}{3}+\frac{x^{4}}{4}\right]^{1}_{0}\\
&=\left(a^{3}+3a^{2}\frac{1}{2}+3a\frac{1}{3}+\frac{1}{4}\right)-0\\
&=\left(a^{3}+\frac{3}{2}a^{2}+a+\frac{1}{4}\right)
\end{align}

<br>

c. Now we can solve the equation given as

\[
\int_{0}^{1}(a+x)^{3}=\frac{1}{4}+\frac{a}{2}
\]
Replacing the left-hand side
\[
a^{3}+\frac{3}{2}a^{2}+a+\frac{1}{4}=\frac{1}{4}+\frac{a}{2}\\
\implies  a^{3}+\frac{3}{2}a^{2}+\frac{a}{2}=0\\
\implies a \left( a^{2}+\frac{3}{2}a+\frac{1}{2}\right)=0
\]
So $a=0$, or
\[
a^{2}+\frac{3}{2}a+\frac{1}{2}=0\\
\]

Completing the square is probably the easiest method to use on this quadratic
\[
a^{2}+\frac{3}{2}a+\frac{1}{2}=(a+\frac{3}{4})^{2}-\frac{9}{16}+\frac{8}{16}=0\\
\implies (a+\frac{3}{4})^{2}=\frac{1}{16}\\
\implies (a+\frac{3}{4})=\pm\sqrt{\frac{1}{16}}=\pm\frac{\sqrt{1}}{\sqrt{16}}=\pm\frac{1}{4}\\
\implies a=-\frac{3}{4}\pm\frac{1}{4}=\frac{-3\pm 1}{4}
\]
So $a=-1$ and $a=-1/2$ from the quadratic. Together with $a=0$, these are the three possible values for $a$.

<br>

__Question 7 is important as it combines elements from many C1 and C2 topics. Known as `multi-step' problems, it is the kind of harder question always asked in exams (typically at the end, but not always). It contains: Binomial expansion, integration, indices, quadratics and the important case where the quadratic is hidden inside another related problem (here the integration). Keep practising it until you feel comfortable with all the steps, and can complete it without looking at my answer. I have put 2 more below.__

<br>

Using the same method as presented in Q7, solve
\[
\int_{-1}^{1}(a-x)^{3}=a^{3}+3a^{2}
\]
Step1. Expand (a-x)^{3} as a binomial sum.

Step2. Carry out the integration on the binomial sum. Because we have limits on the integral, we expect our answer to be some function just involving the (unknown) constant $a$.

Step 3. Solve the equation (just like you solve a quadratic) by replacing the integral with the expression you found in step 2. 

Step 4. You now should just have an a polynomial in $a$ on the left-hand-side. Now you can simplify and solve the cubic equation, bringing all terms to one side and setting the right-hand-side to $0$, to find the possible $a$ values. I am using simple cubics, as it is solving quadratics that is more important for C1/C2.

__Answer:__ $a=0, 1, 2$

<br>

Here there is only one possible value for $a$. This will also test your fractions manipulation. Solve,

\[
\int_{-1}^{0}\left(1-\frac{x}{a}\right)^{3}=1+\frac{1}{4a^{3}}, \quad \textrm{Where } a \neq 0
\]

__Answer:__ $a=-2/3$

<br>

#Basic Revision
Often exam marks can be lost by forgetting how to perform simple manipulations (indices, fractions, etc). It is important to be solid in this area. Use the below, if you need to, to refresh your memory.

#Fractions

Here are some exercises to help cement the basics of indices and fractions. These are important as all C1/C2 questions depend upon a fluent handling of this area.

1. When we write
\[
\frac{x}{4}
\]

We can also write this, using the same multiplication shorthand as learnt at GCSE.
\[
\frac{x}{4}=\frac{1}{4} \times x=\frac{1}{4}(x)=\frac{1}{4}x
\]
This is so, because of the laws of multiplying fractions. In general

\[
\frac{a}{b} \times \frac{x}{y}=\frac{a \times x}{b \times y}=\frac{ax}{by}
\]

Then, working backwards we can take $a=1$, $b=4$ and $y=1$ and we obtain
\[
\frac{x}{4}=\frac{1}{4}\frac{x}{1}=\frac{1}{4}x
\]

<br>

2. When we write 
\[
\frac{1}{\frac{2}{3}}
\]

We should immediately think this is very horrible. We should always try to simplify these sorts of fraction (in general avoid having more than one dividing bar in a fraction...). This situation sometimes arises in integration.

I will use algebra to show what is going on. We want to express this horrible fraction as a proper fraction. That is, as two numbers $a$ and $b$ such that

\[
\frac{1}{\frac{2}{3}}=\frac{a}{b}
\]

So now we can manipulate this. First multiply both sides by $\frac{2}{3}$. This cancels the fraction on the left-hand side

\[
1=\frac{a}{b}\frac{2}{3}=\frac{2a}{3b} \quad \textrm{using the multiplication rule 1, above}
\]

<br>

Now multiply both sides by 3
\[
3 \times 1 = \frac{2a}{3b}\times 3 =\frac{2a \times 3}{3b}=\frac{2a}{b}
\]

Now divide both sides by 2
\[
\frac{3 \times 1 }{2}=\frac{2a}{2b}=\frac{a}{b}
\]

And there is our answer ($a=3$ and $b=2$). So

\[
\frac{1}{\frac{2}{3}}=\frac{3}{2}
\]

In general
\[
\frac{x}{\frac{y}{z}}=x\frac{z}{y}
\]

__All the rules above carry through regardless if fractions are negative__

3. Remember:

\[
-\frac{a}{b}=\frac{-a}{b}=\frac{a}{-b}=-a\frac{1}{b}=a\frac{-1}{b}
\]
All mean the same thing. We change where we put the minus sign, only to make cancellation clearer
\[
\frac{-a}{-b}=\frac{a}{b} \quad \textrm{clearer than,} \quad -\frac{a}{-b}=\frac{a}{b}
\]

#Indices 

These are especially important for C1/C2 - more so than at GCSE. It is important to work through textbook exercises for these, if you feel a little shaky on them, as they are so important for derivatives and integration.

<br>

4. For any number $a$ (positive, negative, fraction, etc), we have:

\[
\left(\frac{x}{y}\right)^{a}=\frac{x^{a}}{y^{a}}, \quad \left(xy \right)^{a}=x^{a}y^{a}
\]

For example, we know $2^{2}=4$. We also know $8/4=2$. So,
\[
2^{2}=\left(\frac{8}{4}\right)^{2}=\frac{8^{2}}{4^{2}}=\frac{64}{16}=\frac{2\times2\times2\times2\times2\times2}{2\times2\times2\times2}=2\times 2=4
\]

Similarly, 

\[
\sqrt{2}=\sqrt{\left(\frac{8}{4}\right)}=\left(\frac{8}{4}\right)^{1/2}=\frac{8^{1/2}}{4^{1/2}}=\frac{(2\times 4)^{1/2}}{4^{1/2}}=\frac{2^{1/2}4^{1/2}}{4^{1/2}}=\frac{\sqrt{2}\sqrt{4}}{\sqrt{4}}=\sqrt{2}
\]

<br>

5. Fractions and differing indices


\[
\frac{x^{a}}{x^{b}}=x^{a-b}
\]

For example
\[
\frac{x^{5}}{x^{2}}=\frac{x \times x \times x\times x\times x }{x \times x}=x \times x \times x=x^{3}=x^{5-2}
\]

This also explains negative indices

\[
\frac{x^{2}}{x^{3}}=\frac{x \times x}{x \times x \times x}=\frac{1}{x}=x^{2-3}=x^{-1}
\]

and

\[
\frac{x^{2}}{x^{5}}=\frac{x \times x}{x \times x \times x \times x \times x}=\frac{1}{x\times x\times x}=\frac{1}{x^{3}}=x^{2-5}=x^{-3}
\]

In general

\[
x^{-a}=\frac{1}{x^{a}} \quad \textrm{and, } \left(\frac{x}{y}\right)^{-a}=\left(\frac{y}{x}\right)^{a}
\]

6. Multiplication of indices and fractional powers

We write
\[
x^{a \times b} = x^{ab}
\]

The best way to think of this is as
\[
x^{ab}=\left(x^{a}\right)^{b}=\left(x^{b}\right)^{a}
\]
Note we can compute the power in stages, in any order we like.

For a fractional power (or rational power as it is also known), we make use of the multiplication rule. Let $b$ and $d$ be whole numbers, so that $b/d$ is a fraction then

\[
x^{b/d}=(x^b)^{1/d}=\sqrt[d]{x^{b}}
\]

Or we can this the other way around, too

\[
x^{b/d}=(x^{1/d})^{b}=\left(\sqrt[d]{x}\right)^{b}
\]

For example
\[
8^{2/3}=(8^{1/3})^{2}=(2)^{2}=4
\]
and
\[
8^{2/3}=(8^{2})^{1/3}=(64)^{1/3}=\sqrt[3]{64}=4
\]

Notice how performing $8^{1/3}$ first is easier than performing $8^{2}$ first. This is often what guides us when deciding what operation to perform first.


